server:
  port: 9000
  servlet:
    context-path: /api
  lazy: true


myapp:
  # 默认创建用户的密码
  password: admin#123456
  # 密码加密的加盐
  password-salt: Admin@salt
  # 开启缓存
  permission-cache: false
  # 是否开启系统日志保存功能
  save-log: true
  # 强密码，为空或者为none表示关闭
  strong-password: 123456
  # 路由放行（用逗号分割）
  excludes: /system/dashboard/index,/system/login,/system/captcha,/
  # 文件存放配置
  file:
    # 默认文件存放位置
    default-path: F:/Files/default/
    # 头像保存位置
    avatar: F:/Files/avatar/
    # 支持上传的文件格式
    support-filetype: pdf,doc,docx,ppt,txt,md,xlsx,xlx,jpg,png
    # 媒体格式
    media-filetype: mp4,avi,mpg,mpeg,wmv,flv,swf,mov,mkv
  # Redis
  rd1:
    server: 127.0.0.1:6379
    db: 1
    password:


# Sa-Token 配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 86400
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: random-64
  # 是否输出操作日志
  is-log: false


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    name: dataSource
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.143:3306/cyrene_admin?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: tester
    password: tester
  # sqltoy框架相关配置
  sqltoy:
    unify-fields-handler: net.cocotea.cyreneadmin.handler.SqlToyUnifyFieldsHandler
    # 配置sql文件路径,多个用逗号分割
    sqlResourcesDir: classpath:sqltoy
    # 默认为false，debug模式将打印执行sql,并自动检测sql文件更新并重新加载
    debug: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB